query FindImages(
  $filter: FindFilterType
  $image_filter: ImageFilterType
  $image_ids: [Int!]
) {
  findImages(
    filter: $filter
    image_filter: $image_filter
    image_ids: $image_ids
  ) {
    count
    images {
      ...SlimImageData
    }
  }
}

query FindImagesMetadata(
  $filter: FindFilterType
  $image_filter: ImageFilterType
  $image_ids: [Int!]
) {
  findImages(
    filter: $filter
    image_filter: $image_filter
    image_ids: $image_ids
  ) {
    megapixels
    filesize
  }
}

query FindImagesForSelect(
  $filter: FindFilterType
  $image_filter: ImageFilterType
  $ids: [ID!]
) {
  findImages(filter: $filter, image_filter: $image_filter, ids: $ids) {
    count
    images {
      ...SelectImageData
    }
  }
}

query FindImage($id: ID!, $checksum: String) {
  findImage(id: $id, checksum: $checksum) {
    ...ImageData
  }
}
