// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AIChatReaderWriter is an autogenerated mock type for the AIChatReaderWriter type
type AIChatReaderWriter struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: ctx, msg
func (_m *AIChatReaderWriter) CreateMessage(ctx context.Context, msg *models.AIChatMessage) error {
	ret := _m.Called(ctx, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AIChatMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSession provides a mock function with given fields: ctx, session
func (_m *AIChatReaderWriter) CreateSession(ctx context.Context, session *models.AIChatSession) error {
	ret := _m.Called(ctx, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AIChatSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, messageID
func (_m *AIChatReaderWriter) DeleteByID(ctx context.Context, messageID string) error {
	ret := _m.Called(ctx, messageID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *AIChatReaderWriter) DeleteBySessionID(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *AIChatReaderWriter) FindAll(ctx context.Context) ([]*models.AIChatSession, error) {
	ret := _m.Called(ctx)

	var r0 []*models.AIChatSession
	if rf, ok := ret.Get(0).(func(context.Context) []*models.AIChatSession); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIChatSession)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *AIChatReaderWriter) FindBySessionID(ctx context.Context, sessionID string) ([]*models.AIChatMessage, error) {
	ret := _m.Called(ctx, sessionID)

	var r0 []*models.AIChatMessage
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.AIChatMessage); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIChatMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetTitle provides a mock function with given fields: ctx, sessionID, title
func (_m *AIChatReaderWriter) SetTitle(ctx context.Context, sessionID string, title string) error {
	ret := _m.Called(ctx, sessionID, title)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sessionID, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Touch provides a mock function with given fields: ctx, sessionID
func (_m *AIChatReaderWriter) Touch(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
