// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AIFileRenameReaderWriter is an autogenerated mock type for the AIFileRenameReaderWriter type
type AIFileRenameReaderWriter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AIFileRenameReaderWriter) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEntity provides a mock function with given fields: ctx, entityType, entityID
func (_m *AIFileRenameReaderWriter) FindByEntity(ctx context.Context, entityType string, entityID int) (*models.AIFileRename, error) {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 *models.AIFileRename
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *models.AIFileRename); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIFileRename)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *AIFileRenameReaderWriter) FindByID(ctx context.Context, id int64) (*models.AIFileRename, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.AIFileRename
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.AIFileRename); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIFileRename)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: ctx, status
func (_m *AIFileRenameReaderWriter) FindByStatus(ctx context.Context, status string) ([]*models.AIFileRename, error) {
	ret := _m.Called(ctx, status)

	var r0 []*models.AIFileRename
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.AIFileRename); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIFileRename)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPendingByEntityType provides a mock function with given fields: ctx, entityType
func (_m *AIFileRenameReaderWriter) FindPendingByEntityType(ctx context.Context, entityType string) ([]*models.AIFileRename, error) {
	ret := _m.Called(ctx, entityType)

	var r0 []*models.AIFileRename
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.AIFileRename); ok {
		r0 = rf(ctx, entityType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIFileRename)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, entityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *AIFileRenameReaderWriter) UpdateStatus(ctx context.Context, id int64, status string) error {
	ret := _m.Called(ctx, id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, rename
func (_m *AIFileRenameReaderWriter) Upsert(ctx context.Context, rename *models.AIFileRename) error {
	ret := _m.Called(ctx, rename)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AIFileRename) error); ok {
		r0 = rf(ctx, rename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
