// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AIMediaQualityReaderWriter is an autogenerated mock type for the AIMediaQualityReaderWriter type
type AIMediaQualityReaderWriter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AIMediaQualityReaderWriter) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAssessedEntities provides a mock function with given fields: ctx, entityType
func (_m *AIMediaQualityReaderWriter) FindAssessedEntities(ctx context.Context, entityType string) ([]int, error) {
	ret := _m.Called(ctx, entityType)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, string) []int); ok {
		r0 = rf(ctx, entityType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, entityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEntity provides a mock function with given fields: ctx, entityType, entityID
func (_m *AIMediaQualityReaderWriter) FindByEntity(ctx context.Context, entityType string, entityID int) (*models.AIMediaQuality, error) {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 *models.AIMediaQuality
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *models.AIMediaQuality); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIMediaQuality)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *AIMediaQualityReaderWriter) FindByID(ctx context.Context, id int64) (*models.AIMediaQuality, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.AIMediaQuality
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.AIMediaQuality); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIMediaQuality)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, quality
func (_m *AIMediaQualityReaderWriter) Upsert(ctx context.Context, quality *models.AIMediaQuality) error {
	ret := _m.Called(ctx, quality)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AIMediaQuality) error); ok {
		r0 = rf(ctx, quality)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
