// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AIMemoryReaderWriter is an autogenerated mock type for the AIMemoryReaderWriter type
type AIMemoryReaderWriter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, key
func (_m *AIMemoryReaderWriter) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAll provides a mock function with given fields: ctx
func (_m *AIMemoryReaderWriter) DeleteAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *AIMemoryReaderWriter) FindAll(ctx context.Context) ([]*models.AIMemory, error) {
	ret := _m.Called(ctx)

	var r0 []*models.AIMemory
	if rf, ok := ret.Get(0).(func(context.Context) []*models.AIMemory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIMemory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByKey provides a mock function with given fields: ctx, key
func (_m *AIMemoryReaderWriter) FindByKey(ctx context.Context, key string) (*models.AIMemory, error) {
	ret := _m.Called(ctx, key)

	var r0 *models.AIMemory
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.AIMemory); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIMemory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, key, value
func (_m *AIMemoryReaderWriter) Set(ctx context.Context, key string, value string) error {
	ret := _m.Called(ctx, key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
