// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AIMoodReaderWriter is an autogenerated mock type for the AIMoodReaderWriter type
type AIMoodReaderWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, mood
func (_m *AIMoodReaderWriter) Create(ctx context.Context, mood *models.AISceneMood) error {
	ret := _m.Called(ctx, mood)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AISceneMood) error); ok {
		r0 = rf(ctx, mood)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBySceneID provides a mock function with given fields: ctx, sceneID
func (_m *AIMoodReaderWriter) DeleteBySceneID(ctx context.Context, sceneID int) error {
	ret := _m.Called(ctx, sceneID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, sceneID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindBySceneID provides a mock function with given fields: ctx, sceneID
func (_m *AIMoodReaderWriter) FindBySceneID(ctx context.Context, sceneID int) ([]*models.AISceneMood, error) {
	ret := _m.Called(ctx, sceneID)

	var r0 []*models.AISceneMood
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.AISceneMood); ok {
		r0 = rf(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AISceneMood)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMoods provides a mock function with given fields: ctx, mood, limit
func (_m *AIMoodReaderWriter) FindMoods(ctx context.Context, mood string, limit int) ([]int, error) {
	ret := _m.Called(ctx, mood, limit)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []int); ok {
		r0 = rf(ctx, mood, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, mood, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoodCounts provides a mock function with given fields: ctx
func (_m *AIMoodReaderWriter) MoodCounts(ctx context.Context) ([]*models.AIMoodCount, error) {
	ret := _m.Called(ctx)

	var r0 []*models.AIMoodCount
	if rf, ok := ret.Get(0).(func(context.Context) []*models.AIMoodCount); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIMoodCount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
