// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AIPerformerSuggestionReaderWriter is an autogenerated mock type for the AIPerformerSuggestionReaderWriter type
type AIPerformerSuggestionReaderWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, suggestion
func (_m *AIPerformerSuggestionReaderWriter) Create(ctx context.Context, suggestion *models.AIPerformerSuggestion) error {
	ret := _m.Called(ctx, suggestion)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AIPerformerSuggestion) error); ok {
		r0 = rf(ctx, suggestion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByPerformerID provides a mock function with given fields: ctx, performerID
func (_m *AIPerformerSuggestionReaderWriter) DeleteByPerformerID(ctx context.Context, performerID int) error {
	ret := _m.Called(ctx, performerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, performerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *AIPerformerSuggestionReaderWriter) FindByID(ctx context.Context, id int64) (*models.AIPerformerSuggestion, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.AIPerformerSuggestion
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.AIPerformerSuggestion); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIPerformerSuggestion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: ctx, status
func (_m *AIPerformerSuggestionReaderWriter) FindByStatus(ctx context.Context, status string) ([]*models.AIPerformerSuggestion, error) {
	ret := _m.Called(ctx, status)

	var r0 []*models.AIPerformerSuggestion
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.AIPerformerSuggestion); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIPerformerSuggestion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPair provides a mock function with given fields: ctx, sourceID, targetID
func (_m *AIPerformerSuggestionReaderWriter) FindPair(ctx context.Context, sourceID int, targetID int) (*models.AIPerformerSuggestion, error) {
	ret := _m.Called(ctx, sourceID, targetID)

	var r0 *models.AIPerformerSuggestion
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.AIPerformerSuggestion); ok {
		r0 = rf(ctx, sourceID, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIPerformerSuggestion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, sourceID, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *AIPerformerSuggestionReaderWriter) UpdateStatus(ctx context.Context, id int64, status string) error {
	ret := _m.Called(ctx, id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusByStatus provides a mock function with given fields: ctx, fromStatus, toStatus
func (_m *AIPerformerSuggestionReaderWriter) UpdateStatusByStatus(ctx context.Context, fromStatus string, toStatus string) (int64, error) {
	ret := _m.Called(ctx, fromStatus, toStatus)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, fromStatus, toStatus)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, fromStatus, toStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
