// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AIPerformerCareerReaderWriter is an autogenerated mock type for the AIPerformerCareerReaderWriter type
type AIPerformerCareerReaderWriter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AIPerformerCareerReaderWriter) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAssessedPerformers provides a mock function with given fields: ctx
func (_m *AIPerformerCareerReaderWriter) FindAssessedPerformers(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPerformerID provides a mock function with given fields: ctx, performerID
func (_m *AIPerformerCareerReaderWriter) FindByPerformerID(ctx context.Context, performerID int) (*models.AIPerformerCareer, error) {
	ret := _m.Called(ctx, performerID)

	var r0 *models.AIPerformerCareer
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.AIPerformerCareer); ok {
		r0 = rf(ctx, performerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIPerformerCareer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, performerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, career
func (_m *AIPerformerCareerReaderWriter) Upsert(ctx context.Context, career *models.AIPerformerCareer) error {
	ret := _m.Called(ctx, career)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AIPerformerCareer) error); ok {
		r0 = rf(ctx, career)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
