// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AIPerformerCandidateReaderWriter is an autogenerated mock type for the AIPerformerCandidateReaderWriter type
type AIPerformerCandidateReaderWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, candidate
func (_m *AIPerformerCandidateReaderWriter) Create(ctx context.Context, candidate *models.AIPerformerCandidate) error {
	ret := _m.Called(ctx, candidate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AIPerformerCandidate) error); ok {
		r0 = rf(ctx, candidate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *AIPerformerCandidateReaderWriter) DeleteByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *AIPerformerCandidateReaderWriter) FindByID(ctx context.Context, id int64) (*models.AIPerformerCandidate, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.AIPerformerCandidate
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.AIPerformerCandidate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIPerformerCandidate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: ctx, status
func (_m *AIPerformerCandidateReaderWriter) FindByStatus(ctx context.Context, status string) ([]*models.AIPerformerCandidate, error) {
	ret := _m.Called(ctx, status)

	var r0 []*models.AIPerformerCandidate
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.AIPerformerCandidate); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIPerformerCandidate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *AIPerformerCandidateReaderWriter) UpdateStatus(ctx context.Context, id int64, status string) error {
	ret := _m.Called(ctx, id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusByStatus provides a mock function with given fields: ctx, fromStatus, toStatus
func (_m *AIPerformerCandidateReaderWriter) UpdateStatusByStatus(ctx context.Context, fromStatus string, toStatus string) (int64, error) {
	ret := _m.Called(ctx, fromStatus, toStatus)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, fromStatus, toStatus)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, fromStatus, toStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
