// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AISavedPlanReaderWriter is an autogenerated mock type for the AISavedPlanReaderWriter type
type AISavedPlanReaderWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, plan
func (_m *AISavedPlanReaderWriter) Create(ctx context.Context, plan *models.AISavedPlan) error {
	ret := _m.Called(ctx, plan)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AISavedPlan) error); ok {
		r0 = rf(ctx, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *AISavedPlanReaderWriter) DeleteByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *AISavedPlanReaderWriter) FindAll(ctx context.Context) ([]*models.AISavedPlan, error) {
	ret := _m.Called(ctx)

	var r0 []*models.AISavedPlan
	if rf, ok := ret.Get(0).(func(context.Context) []*models.AISavedPlan); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AISavedPlan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
