// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AISavedMomentReaderWriter is an autogenerated mock type for the AISavedMomentReaderWriter type
type AISavedMomentReaderWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, saved
func (_m *AISavedMomentReaderWriter) Create(ctx context.Context, saved *models.AISavedMoment) error {
	ret := _m.Called(ctx, saved)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AISavedMoment) error); ok {
		r0 = rf(ctx, saved)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByMarkerID provides a mock function with given fields: ctx, markerID
func (_m *AISavedMomentReaderWriter) DeleteByMarkerID(ctx context.Context, markerID int) error {
	ret := _m.Called(ctx, markerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, markerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *AISavedMomentReaderWriter) FindAll(ctx context.Context) ([]*models.AISavedMoment, error) {
	ret := _m.Called(ctx)

	var r0 []*models.AISavedMoment
	if rf, ok := ret.Get(0).(func(context.Context) []*models.AISavedMoment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AISavedMoment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
