// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AISceneAudioReaderWriter is an autogenerated mock type for the AISceneAudioReaderWriter type
type AISceneAudioReaderWriter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AISceneAudioReaderWriter) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAssessedScenes provides a mock function with given fields: ctx
func (_m *AISceneAudioReaderWriter) FindAssessedScenes(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySceneID provides a mock function with given fields: ctx, sceneID
func (_m *AISceneAudioReaderWriter) FindBySceneID(ctx context.Context, sceneID int) (*models.AISceneAudio, error) {
	ret := _m.Called(ctx, sceneID)

	var r0 *models.AISceneAudio
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.AISceneAudio); ok {
		r0 = rf(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AISceneAudio)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoanLeaderboard provides a mock function with given fields: ctx, limit
func (_m *AISceneAudioReaderWriter) MoanLeaderboard(ctx context.Context, limit int) ([]*models.AIMoanLeaderboardEntry, error) {
	ret := _m.Called(ctx, limit)

	var r0 []*models.AIMoanLeaderboardEntry
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.AIMoanLeaderboardEntry); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AIMoanLeaderboardEntry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByTranscript provides a mock function with given fields: ctx, query, limit
func (_m *AISceneAudioReaderWriter) SearchByTranscript(ctx context.Context, query string, limit int) ([]*models.AISceneAudio, error) {
	ret := _m.Called(ctx, query, limit)

	var r0 []*models.AISceneAudio
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*models.AISceneAudio); ok {
		r0 = rf(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AISceneAudio)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatsByPerformer provides a mock function with given fields: ctx, performerID
func (_m *AISceneAudioReaderWriter) StatsByPerformer(ctx context.Context, performerID int) (*models.AIPerformerAudioStats, error) {
	ret := _m.Called(ctx, performerID)

	var r0 *models.AIPerformerAudioStats
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.AIPerformerAudioStats); ok {
		r0 = rf(ctx, performerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIPerformerAudioStats)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, performerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, audio
func (_m *AISceneAudioReaderWriter) Upsert(ctx context.Context, audio *models.AISceneAudio) error {
	ret := _m.Called(ctx, audio)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AISceneAudio) error); ok {
		r0 = rf(ctx, audio)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
