// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AISuggestionReaderWriter is an autogenerated mock type for the AISuggestionReaderWriter type
type AISuggestionReaderWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, suggestion
func (_m *AISuggestionReaderWriter) Create(ctx context.Context, suggestion *models.AISuggestion) error {
	ret := _m.Called(ctx, suggestion)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AISuggestion) error); ok {
		r0 = rf(ctx, suggestion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AISuggestionReaderWriter) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEntity provides a mock function with given fields: ctx, entityType, entityID
func (_m *AISuggestionReaderWriter) FindByEntity(ctx context.Context, entityType string, entityID int) ([]*models.AISuggestion, error) {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 []*models.AISuggestion
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*models.AISuggestion); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AISuggestion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *AISuggestionReaderWriter) FindByID(ctx context.Context, id int64) (*models.AISuggestion, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.AISuggestion
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.AISuggestion); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AISuggestion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: ctx, status
func (_m *AISuggestionReaderWriter) FindByStatus(ctx context.Context, status string) ([]*models.AISuggestion, error) {
	ret := _m.Called(ctx, status)

	var r0 []*models.AISuggestion
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.AISuggestion); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AISuggestion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPendingByEntityType provides a mock function with given fields: ctx, entityType
func (_m *AISuggestionReaderWriter) FindPendingByEntityType(ctx context.Context, entityType string) ([]*models.AISuggestion, error) {
	ret := _m.Called(ctx, entityType)

	var r0 []*models.AISuggestion
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.AISuggestion); ok {
		r0 = rf(ctx, entityType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AISuggestion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, entityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *AISuggestionReaderWriter) UpdateStatus(ctx context.Context, id int64, status string) error {
	ret := _m.Called(ctx, id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
