// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// EmbeddingReaderWriter is an autogenerated mock type for the EmbeddingReaderWriter type
type EmbeddingReaderWriter struct {
	mock.Mock
}

// CountByEntityType provides a mock function with given fields: ctx
func (_m *EmbeddingReaderWriter) CountByEntityType(ctx context.Context) (map[string]int, error) {
	ret := _m.Called(ctx)

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByEntity provides a mock function with given fields: ctx, entityType, entityID
func (_m *EmbeddingReaderWriter) DeleteByEntity(ctx context.Context, entityType string, entityID int) error {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByEntityType provides a mock function with given fields: ctx, entityType
func (_m *EmbeddingReaderWriter) DeleteByEntityType(ctx context.Context, entityType string) error {
	ret := _m.Called(ctx, entityType)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, entityType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByModel provides a mock function with given fields: ctx, model
func (_m *EmbeddingReaderWriter) DeleteByModel(ctx context.Context, model string) error {
	ret := _m.Called(ctx, model)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEntity provides a mock function with given fields: ctx, entityType, entityID, model
func (_m *EmbeddingReaderWriter) FindByEntity(ctx context.Context, entityType string, entityID int, model string) ([]float32, error) {
	ret := _m.Called(ctx, entityType, entityID, model)

	var r0 []float32
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) []float32); ok {
		r0 = rf(ctx, entityType, entityID, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) error); ok {
		r1 = rf(ctx, entityType, entityID, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEntityType provides a mock function with given fields: ctx, entityType, model
func (_m *EmbeddingReaderWriter) FindByEntityType(ctx context.Context, entityType string, model string) (map[int][]float32, error) {
	ret := _m.Called(ctx, entityType, model)

	var r0 map[int][]float32
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[int][]float32); ok {
		r0 = rf(ctx, entityType, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int][]float32)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, entityType, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNearDuplicates provides a mock function with given fields: ctx, entityType, model, threshold, minGroupSize, maxEntities
func (_m *EmbeddingReaderWriter) FindNearDuplicates(ctx context.Context, entityType string, model string, threshold float64, minGroupSize int, maxEntities int) ([]models.DuplicateGroup, error) {
	ret := _m.Called(ctx, entityType, model, threshold, minGroupSize, maxEntities)

	var r0 []models.DuplicateGroup
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, int, int) []models.DuplicateGroup); ok {
		r0 = rf(ctx, entityType, model, threshold, minGroupSize, maxEntities)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DuplicateGroup)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, float64, int, int) error); ok {
		r1 = rf(ctx, entityType, model, threshold, minGroupSize, maxEntities)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStale provides a mock function with given fields: ctx, entityType, model
func (_m *EmbeddingReaderWriter) FindStale(ctx context.Context, entityType string, model string) ([]int, error) {
	ret := _m.Called(ctx, entityType, model)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []int); ok {
		r0 = rf(ctx, entityType, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, entityType, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasEmbedding provides a mock function with given fields: ctx, entityType, entityID
func (_m *EmbeddingReaderWriter) HasEmbedding(ctx context.Context, entityType string, entityID int) (bool, error) {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, int) bool); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchSimilar provides a mock function with given fields: ctx, entityType, model, query, limit
func (_m *EmbeddingReaderWriter) SearchSimilar(ctx context.Context, entityType string, model string, query []float32, limit int) ([]models.SimilarityResult, error) {
	ret := _m.Called(ctx, entityType, model, query, limit)

	var r0 []models.SimilarityResult
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []float32, int) []models.SimilarityResult); ok {
		r0 = rf(ctx, entityType, model, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SimilarityResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, []float32, int) error); ok {
		r1 = rf(ctx, entityType, model, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, entityType, entityID, model, embedding
func (_m *EmbeddingReaderWriter) Set(ctx context.Context, entityType string, entityID int, model string, embedding []float32) error {
	ret := _m.Called(ctx, entityType, entityID, model, embedding)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string, []float32) error); ok {
		r0 = rf(ctx, entityType, entityID, model, embedding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
